//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace NXBluetoothRemote
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Drawables
        {
            
            public const int icon = 0x7f020000;
        }
        
        public sealed class Layouts
        {
            
            public const int MainLayout = 0x7f030000;
        }
        
        public sealed class Ids
        {
            
            public const int Status = 0x7f040035;
            
            public const int Battery = 0x7f040036;
            
            public const int Connect = 0x7f040037;
            
            public const int countLabel = 0x7f040038;
            
            public const int countBar = 0x7f040039;
            
            public const int delayLabel = 0x7f04003a;
            
            public const int delayBar = 0x7f04003b;
            
            public const int holdLabel = 0x7f04003c;
            
            public const int holdBar = 0x7f04003d;
            
            public const int Shot = 0x7f04003e;
        }
    }
}
